### ISSUE TITLE
Newest Update Shortened the Bluetooth Radius?

### ISSUE THREAD

**Issue by Popedigoz** [Ryochan7/ds4windows-site#2]
Title. Been using my PS4 controller with DS4W for a long time now no problems. Some days ago there was an update to DS4W and I think after that the radius distance from my bluetooth adapter to my controller is very low now. Need to be like 0.5M close, whereas before I could be like ~4-5M away.

**Comment by Popedigoz** [comment]
DS4Windows Version: 3.2.17
OS: Windows 11 Pro 64-bit (10.0, Build 22621)
@Ryochan7

**Comment by Ryochan7** [comment]
DS4Windows reads controllers as HID devices. It has no control over how the controller is handled by the Bluetooth stack. Plus, wrong repo.

Counting this as invalid. If behavior did change it is more likely due to a bad Windows update.
